import NavigationBar from './components/NavigationBar'
import SearchBar from './components/SearchBar'
import AuthContext from './contexts/AuthContext'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContext>
        <div className='flex'>
          <aside>
          <NavigationBar/>
        </aside>
        <main>
          <SearchBar/>
          {children}
        </main>
        </div>
        </AuthContext>
      </body>
    </html>
  )
}
