import NavigationBar from '@/app/components/NavigationBar'
import SearchBar from '@/app/components/SearchBar'
import '@/app/globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <div className='flex'>
      <aside>
        <NavigationBar />
      </aside>
      <main className="flex flex-col overflow-y-scroll w-full max-h-screen">
        <SearchBar />
        {children}
      </main>
    </div>
  )
}
